In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns 

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
df1 = pd.read_csv('chronic_disease2014.csv')

Cardiovascular Disease
Alcohol
Arthritis
Asthma
Cancer
Chronic Kidney Disease
Chronic Obstructive Pulmonary Disease
Mental Health
Tobacco
Overarching Conditions
Oral Health
Reproductive Health
Diabetes
Immunization
Nutrition, Physical Activity, and Weight Status
Disability
Older Adults

- Cardiovascular Disease (Heart attack)
- Alcohol(alcoholic hepatitis)
- Chronic Kidney Disease (Hypertension, Diabetes, Hypothyroidism, Jaundice, Malaria, Osteoarthristis, Paralysis (brain hemorrhage)
- Reproductive Health ( hepatitis,UTI, Gastroenteritis)
- Nutrition, Physical Activity, and Weight Status ( diabetics, Hypertension(HBP), Migraine, Allergy, GERD)
- Tobacco (

In [4]:
# idetify unique valuse in the datasource column
unique_data_sources = df1['DataSource'].unique()
unique_data_sources

array(['NVSS', 'YRBSS', 'PRAMS', 'BRFSS', 'SEDD; SID',
       'Statewide central cancer registries', 'Death Certificate',
       'USRDS', 'CMS Part A Claims Data', 'ACS 1-Year Estimates',
       'CMS CCW', 'HRSA, UDS', 'WFRS', 'NVSS, Mortality',
       'Legal Research', 'APIS', 'AEDS', 'Birth Certificate, NVSS',
       'NSCH', 'Current Population Survey',
       'CDC Breastfeeding Report Card', 'CDC School Health Profiles',
       'National Immunization Survey', 'mPINC',
       "CDC Children's Food Environment State Indicator Report",
       "USDA National Farmers' Market Directory", 'InfoUSA; USDA', 'ASHW',
       'STATE', 'ACS 5-Year Estimates', 'ANRF'], dtype=object)

In [6]:

# Filter the dataset to select only rows where DataSource is Death Certificate
death_certificate_data = df1[df1['DataSource'] == 'Death Certificate']

In [7]:
death_certificate_data.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,DataValue,DataValueAlt,DataValueFootnoteSymbol,DatavalueFootnote,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,GeoLocation,ResponseID,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
281,2010,2014,IL,Illinois,Death Certificate,Cancer,"Cancer of the oral cavity and pharynx, mortality",NaN,NaN,Average Annual Number,108,108.0,NaN,NaN,NaN,NaN,Gender,Female,NaN,NaN,NaN,NaN,POINT (-88.99771017799969 40.48501028300046),NaN,17,CAN,CAN10_2,AVGANNNMBR,GENDER,GENF,NaN,NaN,NaN,NaN
282,2012,2016,MN,Minnesota,Death Certificate,Cancer,"Cancer of the oral cavity and pharynx, mortality",NaN,NaN,Average Annual Number,148,148.0,NaN,NaN,NaN,NaN,Overall,Overall,NaN,NaN,NaN,NaN,POINT (-94.79420050299967 46.35564873600049),NaN,27,CAN,CAN10_2,AVGANNNMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
283,2009,2013,NC,North Carolina,Death Certificate,Cancer,"Cancer of the oral cavity and pharynx, mortality",NaN,NaN,Average Annual Number,194,194.0,NaN,NaN,NaN,NaN,Gender,Male,NaN,NaN,NaN,NaN,POINT (-79.15925046299964 35.466220975000454),NaN,37,CAN,CAN10_2,AVGANNNMBR,GENDER,GENM,NaN,NaN,NaN,NaN
284,2009,2013,ND,North Dakota,Death Certificate,Cancer,"Cancer of the oral cavity and pharynx, mortality",NaN,NaN,Average Annual Number,17,17.0,NaN,NaN,NaN,NaN,Overall,Overall,NaN,NaN,NaN,NaN,POINT (-100.11842104899966 47.47531977900047),NaN,38,CAN,CAN10_2,AVGANNNMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
285,2010,2014,SC,South Carolina,Death Certificate,Cancer,"Cancer of the oral cavity and pharynx, mortality",NaN,NaN,Average Annual Number,120,120.0,NaN,NaN,NaN,NaN,Gender,Male,NaN,NaN,NaN,NaN,POINT (-81.04537120699968 33.998821303000454),NaN,45,CAN,CAN10_2,AVGANNNMBR,GENDER,GENM,NaN,NaN,NaN,NaN

In [9]:
# Get the number of rows in the filtered dataset
num_rows_filtered = death_certificate_data.shape[0]
num_rows_total = df1.shape[0]
num_rows_filtered, num_rows_total

(79872, 1185676)

In [10]:
selected_topics = [
    'Cardiovascular Disease',
    'Alcohol',
    'Chronic Kidney Disease',
    'Reproductive Health',
    'Nutrition, Physical Activity, and Weight Status',
    'Tobacco'
]

In [12]:
#filter data for selected topics
filtered_datasets = {}
for topic in selected_topics:
    filtered_datasets[topic] = death_certificate_data[death_certificate_data['Topic'] == topic]

In [15]:
# Identify the unique values in the topic column within the Death Certificate data
death_certificate_topic = death_certificate_data['Topic'].unique()
death_certificate_topic.tolist()

['Cancer']

In [16]:
df1['DataSource'] == 'Death Certific'

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,DataValue,DataValueAlt,DataValueFootnoteSymbol,DatavalueFootnote,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,GeoLocation,ResponseID,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2010,2010,OR,Oregon,NVSS,Cardiovascular Disease,Mortality from heart failure,NaN,NaN,Number,30,30.0,NaN,NaN,NaN,NaN,Race/Ethnicity,American Indian or Alaska Native,NaN,NaN,NaN,NaN,POINT (-120.15503132599969 44.56744942400047),NaN,41,CVD,CVD1_4,NMBR,RACE,AIAN,NaN,NaN,NaN,NaN
1,2019,2019,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,29.5,29.5,NaN,NaN,24.9,34.7,Gender,Female,NaN,NaN,NaN,NaN,POINT (-111.76381127699972 34.865970280000454),NaN,4,ALC,ALC1_1,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
2,2019,2019,OH,Ohio,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,22.5,22.5,NaN,NaN,17.0,29.1,Gender,Male,NaN,NaN,NaN,NaN,POINT (-82.40426005599966 40.06021014100048),NaN,39,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
3,2019,2019,US,United States,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,13.9,13.9,NaN,NaN,10.4,18.4,Race/Ethnicity,"Asian, non-Hispanic",NaN,NaN,NaN,NaN,NaN,NaN,59,ALC,ALC1_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
4,2015,2015,VI,Virgin Islands,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,NaN,NaN,-,No data available,NaN,NaN,Gender,Male,NaN,NaN,NaN,NaN,POINT (-64.896335 18.335765),NaN,78,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN